cranky: check-control: Only warn for older series (for now)
Don't be too intrusive and fail hard when detecting issues with older
series. Instead just warn and instruct the user to fix the packaging.

Signed-off-by: Juerg Haefliger <juerg.haefliger@canonical.com>
Acked-by: Thibault Ferrante <thibault.ferrante@canonical.com>
Signed-off-by: Juerg Haefliger <juerg.haefliger@canonical.com>

diff --git a/cranky/cmds.d/check-control b/cranky/cmds.d/check-control
--- a/cranky/cmds.d/check-control
+++ b/cranky/cmds.d/check-control
@@ -130,7 +130,14 @@ check_linux_tools
 
 if [ ${RC} -ne 0 ] ; then
 	echo "EE: Some checks failed" >&2
-	exit 1
+	series=$(dpkg-parsechangelog -l"${DEBIAN}"/changelog -SDistribution)
+	if [ "${series}" = "noble" ] ; then
+		exit 1
+	fi
+	echo
+	echo "WW: Please fix the reported packaging issues and/or report them to the kernel owner." >&2
+	echo "WW: This is currently just a warning but will be turned into an error in the future." >&2
+	exit 0
 fi
 
 echo "All checks passed"
