cranky: check-control: Separate out the package stanza checks
Put the package stanza checks into separate functions so that they can
be reused for additional checks.

Signed-off-by: Juerg Haefliger <juerg.haefliger@canonical.com>
Acked-by: Thibault Ferrante <thibault.ferrante@canonical.com>
Signed-off-by: Juerg Haefliger <juerg.haefliger@canonical.com>

diff --git a/cranky/cmds.d/check-control b/cranky/cmds.d/check-control
--- a/cranky/cmds.d/check-control
+++ b/cranky/cmds.d/check-control
@@ -19,36 +19,39 @@ function out()
 	exit ${rc}
 }
 
+
+function must_produce()
+{
+	local package=${1} note=${2:-}
+
+	if ! grep -qP "^Package:\s*${package}$" debian/control ; then
+		echo "EE: debian/control is missing package stanza${note}:" >&2
+		echo "Package: ${package}" >&2
+		RC=1
+	fi
+}
+
+function must_not_produce()
+{
+	local package=${1} note=${2:-}
+
+	if grep -qP "^Package:\s*${package}$" debian/control ; then
+		echo "EE: debian/control contains invalid package stanza${note}:" >&2
+		echo "Package: ${package}" >&2
+		RC=1
+	fi
+}
+
 function check_linux_source()
 {
-	local linux_source
-
 	echo "  - Check linux-source package stanza"
 
-	linux_source=$(grep -P '^Package:\s*linux.*-source-\d+\.\d+\.\d+' debian/control | \
-	               sed 's/^Package:\s*//')
-
-	case "${SOURCE}___${linux_source}" in
-		linux___linux-source-*)
-			# Main kernel package produces linux-source
-			true
-			;;
-		linux-*___)
-			# Non-main kernel package must *not* produce linux-source
-			true
-			;;
-		*)
-			# All other combinations are packaging mistakes
-			if [ -n "${linux_source}" ] ; then
-				echo "EE: debian/control contains invalid package stanza:" >&2
-				echo "Package: ${linux_source}" >&2
-			else
-				echo "EE: debian/control is missing package stanza:" >&2
-				echo "Package: linux-source-PKGVER" >&2
-			fi
-			RC=1
-			;;
-	esac
+	if [ "${SOURCE}" = "linux" ] ; then
+		must_produce "linux-source-\d+\.\d+\.\d+"
+	else
+		must_not_produce "linux-source-\d+\.\d+\.\d+"
+		must_not_produce "${SOURCE}-source-\d+\.\d+\.\d+"
+	fi
 }
 
 function usage()
