cranky/check-control: Warn on released series, fail on devel
Be more conservative for now and emit a warning on released series
and only fail on the current devel series.

Signed-off-by: Juerg Haefliger <juerg.haefliger@canonical.com>
Acked-by: Thibault Ferrante <thibault.ferrante@canonical.com>
Acked-by: Magali Lemes <magali.lemes@canonical.com>
Signed-off-by: Juerg Haefliger <juerg.haefliger@canonical.com>

diff --git a/cranky/cmds.d/check-control b/cranky/cmds.d/check-control
--- a/cranky/cmds.d/check-control
+++ b/cranky/cmds.d/check-control
@@ -186,12 +186,14 @@ echo
 if [ ${RC} -ne 0 ] ; then
 	echo "EE: Some checks failed" >&2
 	series=$(dpkg-parsechangelog -l"${DEBIAN}"/changelog -SDistribution)
-	if [ "${series}" = "noble" ] ; then
-		exit 1
-	fi
-	echo "WW: Please fix the reported packaging issues and/or report them to the kernel owner." >&2
-	echo "WW: This is currently just a warning but will be turned into an error in the future." >&2
-	exit 0
+	case "${series}" in
+		trusty|xenial|bionic|focal|jammy|noble)
+			echo "WW: Please fix the reported packaging issues and/or report them to the kernel owner." >&2
+			echo "WW: This is currently just a warning but will be turned into an error in the future." >&2
+			exit 0
+			;;
+	esac
+	exit 1
 fi
 
 echo "All checks passed"
