cranky: Trim trailing whitespaces from affected subcommands
https://warthogs.atlassian.net/browse/KERNTT-647
Signed-off-by: Juerg Haefliger <juerg.haefliger@canonical.com>

diff --git a/cranky/cmds.d/review-master-changes b/cranky/cmds.d/review-master-changes
--- a/cranky/cmds.d/review-master-changes
+++ b/cranky/cmds.d/review-master-changes
@@ -69,11 +69,11 @@ version2commit() {
 		exit 1
 	fi
 
-	# Get the commit message for the previous base version		
-	prev_commit_message=$(git rev-list --format=%s --max-count=1 FETCH_HEAD | tail +2)		
-	if [ -z "$prev_commit_message" ]; then		
-		echo "Failed to get commit message for tag \"$base_tag\""		
-		exit 1		
+	# Get the commit message for the previous base version
+	prev_commit_message=$(git rev-list --format=%s --max-count=1 FETCH_HEAD | tail +2)
+	if [ -z "$prev_commit_message" ]; then
+		echo "Failed to get commit message for tag \"$base_tag\""
+		exit 1
 	fi
 
 	# Find the previous commit ID in the current tree
