cranky: Replace all occurences of 'cranky-<foo>' with 'cranky <foo>'
Make the documenstation and output of the tools consistent to only show
the new (and only) usage 'cranky <foo>'.

While at it, fix the Python scripts to show 'cranky <foo>' as the program's
name, rather than just '<foo>'.

Signed-off-by: Juerg Haefliger <juergh@canonical.com>
Acked-by: Marcelo Henrique Cerri <marcelo.cerri@canonical.com>
Acked-by: Stefan Bader <stefan.bader@canonical.com>
Signed-off-by: Juerg Haefliger <juergh@canonical.com>

diff --git a/cranky/cmds.d/tag b/cranky/cmds.d/tag
--- a/cranky/cmds.d/tag
+++ b/cranky/cmds.d/tag
@@ -67,7 +67,7 @@ debug_log "Changelog file: $changelog_file"
 # Check if changelog is open
 series=$(dpkg-parsechangelog -l"$changelog_file" -SDistribution)
 if [ "$series" = 'UNRELEASED' ]; then
-        echo "error: changelog isn't properly closed. Do you need to run cranky-close first?" >&2
+        echo "error: changelog isn't properly closed. Do you need to run cranky close first?" >&2
         exit 1
 fi
 
