cranky: update-dependent -- move logic into a function
Move all core logic into a function so it can be reused more easily.

Signed-off-by: Cory Todd <cory.todd@canonical.com>

diff --git a/cranky/cmds.d/update-dependent b/cranky/cmds.d/update-dependent
--- a/cranky/cmds.d/update-dependent
+++ b/cranky/cmds.d/update-dependent
@@ -3,6 +3,97 @@
 # Update a dependent package (-meta, -signed, ...)
 #
 
+function update_dependent()
+{
+	local ignore_abi_check="${1}"
+
+	if ! [ -d debian ] || ! [ -f update-version ] ; then
+		echo "This is not a dependent kernel package repo" >&2
+		exit 1
+	fi
+
+	# Sanity check: The repo must be clean
+	if [ -n "$(git status --porcelain)" ] ; then
+		echo "Repo is not clean" >&2
+		exit 1
+	fi
+
+	# Get the path to the main package
+	main_path=$("$C" shell-helper tree-main-path .)
+	if [ -z "${main_path}" ] ; then
+		echo "Main kernel source path not found" >&2
+		exit 1
+	fi
+
+	# Run cranky fix as step 1.
+	"$C" fix
+
+	# Get main package details (distro, version, ABI, ...)
+	# shellcheck disable=SC1090,SC1091 # do not make shellcheck validate this env
+	. "${main_path}"/debian/debian.env
+	main_changelog="${main_path}/${DEBIAN}"/changelog
+	main_distro=$(dpkg-parsechangelog -l "${main_changelog}" -S Distribution)
+	main_version=$(dpkg-parsechangelog -l "${main_changelog}" -S Version)
+	main_abi=${main_version%~*}
+	main_abi=$(echo "$main_abi" | sed -ne 's/\([0-9]*\.[0-9]*\.[0-9]*-[0-9]*\)\..*/\1/p')
+
+	# Get the dependent package details
+	dep_distro=$(dpkg-parsechangelog -S Distribution)
+	dep_version=$(dpkg-parsechangelog -S Version)
+	dep_abi=${dep_version%~*}
+	dep_abi=$(echo "$dep_abi" | sed -ne 's/\([0-9]*\.[0-9]*\.[0-9]*[-\.][0-9]*\)\..*/\1/p')
+
+	# Replace last '.' with '-' in -meta package ABI version
+	# shellcheck disable=SC2001
+	dep_abi_dash=$(echo "${dep_abi}" | sed -e 's,\.\([0-9]*\)$,-\1,')
+
+	# Sanity check: The distros must match
+	if [ "${main_distro}" != "${dep_distro}" ] ; then
+		echo "Incorrect main package distro: ${main_distro} (!= ${dep_distro})" >&2
+		exit 1
+	fi
+
+	# Sanity check: The main package ABI version must not be lower
+	upload_bump=0
+	if dpkg --compare-versions "${main_abi}" lt "${dep_abi_dash}" ; then
+		echo "Main package ABI version is lower: ${main_abi} (< ${dep_abi})" >&2
+		if [ -z "$ignore_abi_check" ]; then
+			echo "Use --ignore-abi-check to proceed anyway."
+			exit 1
+		fi
+		upload_bump=1
+	fi
+
+	# Update the changelog and capture stdout
+	readarray -t stdout < <(./update-version "${main_path}")
+
+	# Usually `update-version' will produce a changelog version without entries
+	# for a re-spin (new version with the same ABI). In that case, add a generic
+	# changelog entry.
+	if [ "$upload_bump" -gt 0 ]; then
+		echo -e "\\033[1;31mWarning: Please review the changelog and add a new entry if applicable!\\033[0m" >&2
+		dch -a 'Bump upload number.'
+	fi
+
+	# Cycle through stdout, print each line and look for the 'git commit' line
+	commit_cmd=
+	for line in "${stdout[@]}" ; do
+		echo "${line}"
+		if [ "${line#git commit}" != "${line}" ] ; then
+			commit_cmd=${line}
+		fi
+	done
+
+	if [ -z "${commit_cmd}" ] ; then
+		echo "Commit line not found in output of ./update-version" >&2
+		exit 1
+	fi
+
+	# Commit the changelog
+	sh -c "${commit_cmd}"
+
+}
+
 function usage()
 {
 	cat <<EOF
@@ -38,87 +129,4 @@ while [ $# -gt 0 ] ; do
 	shift
 done
 
-if ! [ -d debian ] || ! [ -f update-version ] ; then
-	echo "This is not a dependent kernel package repo" >&2
-	exit 1
-fi
-
-# Sanity check: The repo must be clean
-if [ -n "$(git status --porcelain)" ] ; then
-	echo "Repo is not clean" >&2
-	exit 1
-fi
-
-# Get the path to the main package
-main_path=$("$C" shell-helper tree-main-path .)
-if [ -z "${main_path}" ] ; then
-	echo "Main kernel source path not found" >&2
-	exit 1
-fi
-
-# Run cranky fix as step 1.
-"$C" fix
-
-# Get main package details (distro, version, ABI, ...)
-# shellcheck disable=SC1090,SC1091 # do not make shellcheck validate this env
-. "${main_path}"/debian/debian.env
-main_changelog="${main_path}/${DEBIAN}"/changelog
-main_distro=$(dpkg-parsechangelog -l "${main_changelog}" -S Distribution)
-main_version=$(dpkg-parsechangelog -l "${main_changelog}" -S Version)
-main_abi=${main_version%~*}
-main_abi=$(echo "$main_abi" | sed -ne 's/\([0-9]*\.[0-9]*\.[0-9]*-[0-9]*\)\..*/\1/p')
-
-# Get the dependent package details
-dep_distro=$(dpkg-parsechangelog -S Distribution)
-dep_version=$(dpkg-parsechangelog -S Version)
-dep_abi=${dep_version%~*}
-dep_abi=$(echo "$dep_abi" | sed -ne 's/\([0-9]*\.[0-9]*\.[0-9]*[-\.][0-9]*\)\..*/\1/p')
-
-# Replace last '.' with '-' in -meta package ABI version
-# shellcheck disable=SC2001
-dep_abi_dash=$(echo "${dep_abi}" | sed -e 's,\.\([0-9]*\)$,-\1,')
-
-# Sanity check: The distros must match
-if [ "${main_distro}" != "${dep_distro}" ] ; then
-	echo "Incorrect main package distro: ${main_distro} (!= ${dep_distro})" >&2
-	exit 1
-fi
-
-# Sanity check: The main package ABI version must not be lower
-upload_bump=0
-if dpkg --compare-versions "${main_abi}" lt "${dep_abi_dash}" ; then
-	echo "Main package ABI version is lower: ${main_abi} (< ${dep_abi})" >&2
-	if [ -z "$ignore_abi_check" ]; then
-		echo "Use --ignore-abi-check to proceed anyway."
-		exit 1
-	fi
-	upload_bump=1
-fi
-
-# Update the changelog and capture stdout
-readarray -t stdout < <(./update-version "${main_path}")
-
-# Usually `update-version' will produce a changelog version without entries
-# for a re-spin (new version with the same ABI). In that case, add a generic
-# changelog entry.
-if [ "$upload_bump" -gt 0 ]; then
-	echo -e "\\033[1;31mWarning: Please review the changelog and add a new entry if applicable!\\033[0m" >&2
-	dch -a 'Bump upload number.'
-fi
-
-# Cycle through stdout, print each line and look for the 'git commit' line
-commit_cmd=
-for line in "${stdout[@]}" ; do
-	echo "${line}"
-	if [ "${line#git commit}" != "${line}" ] ; then
-		commit_cmd=${line}
-	fi
-done
-
-if [ -z "${commit_cmd}" ] ; then
-	echo "Commit line not found in output of ./update-version" >&2
-	exit 1
-fi
-
-# Commit the changelog
-sh -c "${commit_cmd}"
+update_dependent "$ignore_abi_check"
