cranky: update-dependents -- exit on error
Maintain exit-on-error behavior with the option to override using 
--rollback. The call to update-dependent does not exit immediately since
we _may_ need to rollback. All other non-zero return codes will abort as 
expected. Stop processing packages once the first error is encountered
in order to be consistent with the other cranky commands.

Without --rollback, the user may end up in an inconsistent state where
one package succeeds while one or more remain unchanged.

Signed-off-by: Cory Todd <cory.todd@canonical.com>

diff --git a/cranky/cmds.d/update-dependents b/cranky/cmds.d/update-dependents
--- a/cranky/cmds.d/update-dependents
+++ b/cranky/cmds.d/update-dependents
@@ -1,4 +1,4 @@
-#!/bin/bash -u
+#!/bin/bash -eu
 #
 # Update all dependent packages (-meta, -signed, ...)
 #
@@ -19,20 +19,27 @@ Note: Arguments must match update-dependent
 
 Optional arguments:
   -h, --help            Show this help text and exit.
+  -r, --rollback        Automatically rollback on failure
   --ignore-abi-check    Ignore ABI check (when preparing re-spins).
 
 Examples:
   $ cranky update-dependents
-	  Iterate over all dependent packages of jammy:linux-oracle and run
-	  cranky update-dependent against them.
+      Iterate over all dependent packages of jammy:linux-oracle and run
+      cranky update-dependent against them.
 EOF
 	exit 2
 }
 
+rollback_on_error=
 for arg in "$@" ; do
 	case "${arg}" in
 		-h|--help)
 			usage
+			;;
+		# Consume options that should not be forwarded to update-dependent
+		-r|--rollback)
+			rollback_on_error=1
+			shift
 			;;
 	esac
 done
@@ -41,7 +48,6 @@ done
 # If any one tree fails to update, revert them all to their
 # starting states which is their current HEAD reference.
 declare -A tree_states
-any_failed=
 
 readarray -t package_paths < <("$C" shell-helper source-packages-path)
 if [ "${#package_paths[@]}" -eq 0 ] ; then
@@ -57,42 +63,35 @@ for path in "${package_paths[@]}"; do
 		continue
 	fi
 
-	# Avoid missing packages, they make error handling much harder
-	if [ ! -d "${path}" ] ; then
-		echo "Package path not found ${path}" >&2
-		any_failed=1
-		continue
-	fi
-
 	# Capture HEAD as our rollback point
 	tree_states["${path}"]=$(git -C "$path" rev-parse HEAD)
 
 	# Run update process from the package's tree path
+	rc=0
 	(
 		echo "Updating dependent: ${path}"
-		cd "${path}" || return 1
+		cd "${path}" || exit 1
 		"$C" update-dependent "$@"
-	);
-	rc=$?
+	) || rc=1;
+
 	if [[ $rc -ne 0 ]] ; then
-		echo "ERROR: Failed to update dependent ${path}" >&2
-		any_failed=1
+	
+		# Roll back all trees to their starting points
+		if [[ -n $rollback_on_error ]] ; then
+			echo "ERROR: Update failed, reverting all changes..." >&2
+			for x in "${!tree_states[@]}" ; do
+				sha="${tree_states[$x]}"
+				echo "Reverting ${x} to $sha" >&2
+				git -C "${x}" reset --hard "$sha" > /dev/null
+			done
+			echo "ERROR: Failed to update dependent ${path}" >&2
+		else
+			echo "ERROR: Your package trees may be in an inconsistent state" >&2
+			echo "ERROR: In the future, use --rollback to recover from this" >&2
+		fi
+
+		exit 1
 	fi
 done
-
-if [ -n "$any_failed" ] ; then
-	# Roll back all trees to their starting points
-	echo "Rolling back update..." >&2
-
-	for path in "${!tree_states[@]}" ; do
-		sha="${tree_states[$path]}"
-		echo "Reverting ${path} to $sha" >&2
-		git -C "${path}" reset --hard "$sha"
-	done
-
-	echo "Rollback complete" >&2
-	echo "ERROR: One or more packages could not be updated" >&2
-	exit 1
-fi
 
 echo "SUCCESS: update complete"
