cranky/cmds.d/update-dkms-versions: add support for absolute references
We have a big problem with dkms-versions for Nvidia becoming out of sync
between cycles, particularly when creating new cycles in parallel with
the Nvidia versions changing.  In order to avoid this we desire the
Nvidia versions to be consistent in all cycles.  Add support for
absolute references outside of the cycle.  We will use this to implement
a /common/dkms-versions containing the Nvidia data.

Signed-off-by: Andy Whitcroft <apw@canonical.com>

diff --git a/cranky/cmds.d/update-dkms-versions b/cranky/cmds.d/update-dkms-versions
--- a/cranky/cmds.d/update-dkms-versions
+++ b/cranky/cmds.d/update-dkms-versions
@@ -142,13 +142,14 @@ fi
 	git fetch --quiet --prune "${remote_name}"
 )
 
+git_prefix=${remote_name}/${remote_branch}:
 obj_type=$(git -C "${kv_repo}" cat-file -t "${remote_name}/${remote_branch}:devel" 2>/dev/null || true)
 if [ -n "${obj_type}" ] ; then
-	git_base_devel=${remote_name}/${remote_branch}:devel
+	git_base_devel=${git_prefix}devel
 else
-	git_base_devel=${remote_name}/${remote_branch}:tip
+	git_base_devel=${git_prefix}tip
 fi
-git_base=${remote_name}/${remote_branch}:${sru_cycle}
+git_base=${git_prefix}${sru_cycle}
 git_human=${remote_name}/${sru_cycle}
 
 # Determine if we have this cycle
@@ -224,8 +225,13 @@ dkms_versions=${DEBIAN}/dkms-versions
 
 rm -f "${dkms_versions}".new
 for versions_path in "${versions_paths[@]}" ; do
-	if ! (git -C "${kv_repo}" cat-file -p "${git_base}/${versions_path}") >> "${dkms_versions}".new ; then
-		echo "Unable to download an updated dkms-versions file" 2>&1
+	# Handle / prefix as absolute within the path.
+	case "$versions_path" in
+	/*)	path=${git_prefix}${versions_path#/} ;;
+	*)	path=${git_base}/${versions_path} ;;
+	esac
+	if ! (git -C "${kv_repo}" cat-file -p "${path}") >> "${dkms_versions}".new ; then
+		echo "Unable to download an updated dkms-versions file (path=$path)" 2>&1
 		exit 1
 	fi
 done
