sbin/cron-start: add --no-report support
Allow us to disable reporting to the dashboard.  We still expect
(and then ignore) the dashboard configuration options.

Change-Id: Ic3f380936f553ddf32a561bb2349bde6ffe9ae7d
Signed-off-by: Andy Whitcroft <apw@canonical.com>

diff --git a/sbin/cron-start b/sbin/cron-start
--- a/sbin/cron-start
+++ b/sbin/cron-start
@@ -6,16 +6,31 @@ case "$here" in
 *)  here="`pwd`/$here" ;;
 esac
 
+report='y'
 instance=''
-case "$1" in
---instance)
-	instance="$2"
-	shift 2
-	;;
-esac
+while :
+do
+	case "$1" in
+	--instance)
+		instance="$2"
+		shift 2
+		;;
+	--report)
+		report=y
+		shift 1
+		;;
+	--no-report)
+		report=
+		shift 1
+		;;
+	*)
+		break
+		;;
+	esac
+done
 
 if [ "$#" -lt 6 ]; then
-	echo "Usage: $0 [--instance <instance>] <daemon> ... -- <group> <title> <warn> <alert> ..." 1>&2
+	echo "Usage: $0 [--instance <instance>] [--[no-]report] <daemon> ... -- <group> <title> <warn> <alert> ..." 1>&2
 	exit 1
 fi
 
@@ -50,7 +65,9 @@ lck="/tmp/$name.lck"
 	"$daemon" "${args[@]}" &
 ) 9>"$lck"
 
-# Attempt to re-grab an exclusive lock, if this succeeds then the daemon has
-# failed to start.  Timeout after 5s.
-flock -w 5 -x "$lck" -c "exit 0" || \
-    $here/../dashboard/dashboard-status "cron-start-$name" "$@"
+if [ "$report" ]; then
+	# Attempt to re-grab an exclusive lock, if this succeeds then the daemon has
+	# failed to start.  Timeout after 5s.
+	flock -w 5 -x "$lck" -c "exit 0" || \
+	    $here/../dashboard/dashboard-status "cron-start-$name" "$@"
+fi
