announce: announcer-shankbot -- add retest support
Signed-off-by: Andy Whitcroft <apw@canonical.com>

diff --git a/announce/announcer-shankbot-dispatch b/announce/announcer-shankbot-dispatch
--- a/announce/announcer-shankbot-dispatch
+++ b/announce/announcer-shankbot-dispatch
@@ -39,6 +39,24 @@ shank)
 
 	"$here/../sbin/oops-run" shiv-shank "$here/../stable/swm-hero" "$@"
 	;;
+retest)
+	if [ "$#" -lt 1 ]; then
+		echo "Usage: retest <bug> ..." 1>&2
+		exit 1
+	fi
+	for bug in "$@"
+	do
+		validator=$(echo "$bug" | sed -e 's/[0-9][0-9]*/0/g')
+		case "$validator" in
+		0)		;;
+		*)
+			echo "retest $bug: Invalid bug number" 1>&2
+			exit 1
+			;;
+		esac
+		"$here/../sbin/oops-run" shiv-retest "$here/../stable/tbt" retest "$@"
+	done
+	;;
 *)
 	echo "shankbot: $cmd: unknown command"
 	exit 1
