cranky: tag helper: Replace an existing tag when --force is specified
In case of a cranky re-run, a tag might need to be replaced. Do that when
--force is specified. While at it, cleanup some of the error messages, send
them to stderr and cleanup the usage.

Acked-by: Andrea Righi <andrea.righi@canonical.com>
Signed-off-by: Juerg Haefliger <juergh@canonical.com>

diff --git a/cranky/master-helpers/tag b/cranky/master-helpers/tag
--- a/cranky/master-helpers/tag
+++ b/cranky/master-helpers/tag
@@ -8,16 +8,15 @@ function debug_log()
 function usage()
 {
 	cat <<EOF
-Usage: ${P:-$(basename "$0")} [-h|--help] [-v|--verbose] [-f|--force]
+Usage: ${P:-$(basename "$0")} [-h] [-f] [-v]
 
 Tag the current Ubuntu kernel git tree with the correct version tag.
 
 Optional arguments:
-  -h, --help                         Show this help message and exit.
-  -v, --verbose                      Show extra info when running
-  -f, --force                        Tag the topmost commit even if the commit subject doesn't match expected template
-
-
+  -h, --help     Show this help message and exit.
+  -f, --force    Tag the topmost commit even if its subject is not in the
+                 expected format. Also replace a tag if it already exists.
+  -v, --verbose  Show extra info when running.
 EOF
 	exit 2
 }
@@ -36,7 +35,7 @@ while [ "${#}" -gt 0 ] ; do
 			force=1
 			;;
 		*)
-			echo "error: Unrecognized argument ${1}"
+			echo "error: Unrecognized argument ${1}" >&2
 			usage
 			;;
 	esac
@@ -44,14 +43,14 @@ while [ "${#}" -gt 0 ] ; do
 done
 
 if [ ! -f debian/debian.env ] ; then
-	echo "error: No debian/debian.env found. Is this an Ubuntu kernel source tree?"
+	echo "error: No debian/debian.env found. Is this an Ubuntu kernel source tree?" >&2
 	exit 1
 fi
 
 # shellcheck disable=SC1091
 . debian/debian.env
 if [ -z "${DEBIAN:-}" ] ; then
-	echo "error: Can't find 'DEBIAN' variable in debian/debian.env"
+	echo "error: Can't find 'DEBIAN' variable in debian/debian.env" >&2
 	exit 1
 fi
 debug_log "DEBIAN: $DEBIAN"
@@ -62,14 +61,14 @@ debug_log "Changelog file: $changelog_file"
 # Check if changelog is open
 series=$(dpkg-parsechangelog -l"$changelog_file" -SDistribution)
 if [ "$series" = 'UNRELEASED' ]; then
-        echo "error: changelog isn't properly closed. Do you need to run cranky-close first?"
+        echo "error: changelog isn't properly closed. Do you need to run cranky-close first?" >&2
         exit 1
 fi
 
 
 if ! git show --name-only --format= | grep "$changelog_file" > /dev/null ; then
-	echo "error: No delta in $changelog_file in latest commit"
-	echo "Are you sure the topmost commit is a closing commit?"
+	echo "error: No delta in $changelog_file in latest commit" >&2
+	echo "Are you sure the topmost commit is a closing commit?" >&2
 	exit 1
 fi
 
@@ -83,10 +82,11 @@ new_tag_unfixed="$prefix$new_version"
 debug_log "Tag message: $new_tag_unfixed"
 
 if ! git show -s --format=%s | grep -q "^UBUNTU: $new_tag_unfixed$" ; then
-	echo "error: Topmost commit subject does not include the right content"
-	echo "Closing commit subject should have the first line: "
-	echo "   UBUNTU: $new_tag_unfixed"
-	if [ $force -ne 1 ] ; then
+	echo "error: Topmost commit subject does not include the right content" >&2
+	echo "Closing commit subject should be:" >&2
+	echo "   UBUNTU: $new_tag_unfixed" >&2
+	if [ $force -eq 0 ] ; then
+		echo "Use -f, --force to tag the commit anyways" >&2
 		exit 1
 	else
 		echo "(--force specified - continuing anyway)"
@@ -98,9 +98,18 @@ fi
 new_tag_fixed="${new_tag_unfixed//\~/_}"
 debug_log "New tag: $new_tag_fixed"
 
+if git rev-parse "${new_tag_fixed}" >/dev/null 2>&1 ; then
+	echo "error: Tag '${new_tag_fixed}' exists already" >&2
+	if [ $force -eq 0 ] ; then
+		echo "Use -f, --force to replace it" >&2
+		exit 1
+	else
+		echo "(--force specified - continuing anyway)"
+	fi
+fi
 
 # OK, everything looks good. Tag it.
-tag_cmd="git tag -s -m $new_tag_unfixed $new_tag_fixed"
+tag_cmd="git tag -f -s -m $new_tag_unfixed $new_tag_fixed"
 echo "Tagging with:"
 echo " $tag_cmd"
 
