ancillary-bot/ancillary-{lookup,builder}: use kernel-series adjunct marker
Currently builder assumes all ancillaries are adjunct except for
linux-generate.  ancillary-lookup knows which are adjunct and uses this
to select an appropriate PPA to scan so it makes sense for it to expose
this information to ancillary-builder.

Add the selected destination (primary or adjunct) reference to the
result rows.  Also add the visibility (Public or Private) for that
destination to allow ancillary-builder to perform last ditch checks to
prevent linux-restricted-* being uploaded to a public destination.

Signed-off-by: Andy Whitcroft <apw@canonical.com>

diff --git a/ancillary-bot/ancillary-builder b/ancillary-bot/ancillary-builder
--- a/ancillary-bot/ancillary-builder
+++ b/ancillary-bot/ancillary-builder
@@ -18,7 +18,7 @@ ignore="IGNORE-BUILD"
 [ ! -f "$ignore" ] && touch "$ignore"
 
 "$here/ancillary-lookup" "$ppa" "$ppa_ps" "$ignore" | \
-while read id source urls
+while read id source upload_to visibility urls
 do
 	if [ "$urls" = '-' ]; then
 		if [ -d "$id" ]; then
@@ -45,11 +45,15 @@ do
 			for upload in *_source.changes
 			do
 				case "$upload" in
-				linux-generate*)	upload_to="$ppa"; upload_name="public" ;;
-				*)			upload_to="$ppa_ps"; upload_name="private" ;;
+				linux-restricted-*)
+					if [ "$visibility" != "private" ]; then
+						echo "ERROR: $id: attempting to upload $upload to $visibility PPA" 1>&2
+						exit 1
+					fi
+					;;
 				esac
-				echo "$id: re-uploading $upload (to $upload_name $upload_to) ..."
-				dput ${ANCILLARY_DPUTCF:+-c $ANCILLARY_DPUTCF} "$upload_to" "$upload"
+				echo "$id: re-uploading $upload (to $visibility $upload_to) ..."
+				timeout 5m dput ${ANCILLARY_DPUTCF:+-c $ANCILLARY_DPUTCF} "$upload_to" "$upload"
 			done
 		)
 		arc="$?"
@@ -104,10 +108,14 @@ do
 		for upload in *_source.changes
 		do
 			case "$upload" in
-			linux-generate*)	upload_to="$ppa"; upload_name="public" ;;
-			*)			upload_to="$ppa_ps"; upload_name="private" ;;
+			linux-restricted-*)
+				if [ "$visibility" != "private" ]; then
+					echo "ERROR: $id: attempting to upload $upload to $visibility PPA" 1>&2
+					exit 1
+				fi
+				;;
 			esac
-			echo "$id: uploading $upload (to $upload_name $upload_to) ..."
+			echo "$id: uploading $upload (to $visibility $upload_to) ..."
 			timeout 5m dput ${ANCILLARY_DPUTCF:+-c $ANCILLARY_DPUTCF} "$upload_to" "$upload"
 		done
 	)
