ancillary-bot: add support for internal gen-ancillary support
Add support for gen-ancillary driven ancillaries.  Generalise
unrecognised package forms while we are here.

Signed-off-by: Andy Whitcroft <apw@canonical.com>

diff --git a/ancillary-bot/ancillary-builder b/ancillary-bot/ancillary-builder
--- a/ancillary-bot/ancillary-builder
+++ b/ancillary-bot/ancillary-builder
@@ -24,16 +24,21 @@ do
 	fi
 
 	if [ -d "$id" ]; then
-		if [ ! -f $source-*/debian/scripts/gen-rules.lrm ]; then
-			echo "$id: ignored (v3)"
+		if [ -f "$id/ignore" ]; then
+			echo "$id: non-ancillary form, ignored"
 			continue
 		fi
 		(
 			cd "$id" || exit 1
 			# If the uploads failed, the we should retry them periodically.
-			for changes in *_source.changes
+			for upload in *_source.changes
 			do
-				dput ${ANCILLARY_DPUTCF:+-c $ANCILLARY_DPUTCF} "$ppa_ps" "$changes"
+				case "$upload" in
+				linux-generate*)	upload_to="$ppa"; upload_name="public" ;;
+				*)			upload_to="$ppa_ps"; upload_name="private" ;;
+				esac
+				echo "$id: re-uploading $upload (to $upload_name $upload_to) ..."
+				dput ${ANCILLARY_DPUTCF:+-c $ANCILLARY_DPUTCF} "$upload_to" "$upload"
 			done
 		) || exit "$?"
 		echo "$id: complete"
@@ -54,28 +59,54 @@ do
 		dpkg-source -x $source*.dsc
 
 		# Confirm this is the appropriate form.
-		if [ ! -f $source-*/debian/scripts/gen-rules.lrm ]; then
-			echo "$id: not LRMv4 form, ignored"
+		if [ -f $source-*/debian/scripts/gen-ancillary ]; then
+			echo "$id: triggering gen-anciallary"
+			(
+				cd $source-* || exit 2
+				./debian/scripts/gen-ancillary
+				rc="$?"
+				if [ "$rc" != 0 ]; then
+					echo "$id: gen-ancillary failed rc=$rc" 1>&2
+				fi
+				exit "$rc"
+			) || exit "$?"
+		
+		elif [ -f $source-*/debian/scripts/gen-rules.lrm ]; then
+			(
+				cd $source-* || exit 2
+
+				echo "$id: building linux-restricted-generate ..."
+				sed -i -e '1s/linux-restricted-modules/linux-restricted-generate/' debian/changelog
+				debian/rules clean
+				dpkg-buildpackage --no-sign -nc -S
+
+				echo "$id: building linux-restricted-signatures ..."
+				sed -i -e '1s/linux-restricted-generate/linux-restricted-signatures/' debian/changelog
+				debian/rules clean
+				dpkg-buildpackage --no-sign -nc -S
+			) || exit "$?"
+
+		else
+			echo "$id: non-ancillary form, marking ignored"
+			touch "ignore"
 			exit 0
 		fi
-		(
-			cd $source-* || exit 2
 
-			echo "$is: building linux-restricted-generate ..."
-			sed -i -e '1s/linux-restricted-modules/linux-restricted-generate/' debian/changelog
-			debian/rules clean
-			dpkg-buildpackage --no-sign -nc -S
-
-			echo "$is: building linux-restricted-signatures ..."
-			sed -i -e '1s/linux-restricted-generate/linux-restricted-signatures/' debian/changelog
-			debian/rules clean
-			dpkg-buildpackage --no-sign -nc -S
-		) || exit "$?"
-
-		echo "$i: signing uploads ..."
-		debsign ${ANCILLARY_KEYID:+-k $ANCILLARY_KEYID} *_source.changes
-
-		echo "$i: uploading ..."
-		dput ${ANCILLARY_DPUTCF:+-c $ANCILLARY_DPUTCF} "$ppa_ps" *_source.changes
-	) || exit "$?"
+		for upload in *_source.changes
+		do
+			echo "$id: signing $upload ..."
+			debsign ${ANCILLARY_KEYID:+-k $ANCILLARY_KEYID} "$upload"
+		done
+		for upload in *_source.changes
+		do
+			case "$upload" in
+			linux-generate*)	upload_to="$ppa"; upload_name="public" ;;
+			*)			upload_to="$ppa_ps"; upload_name="private" ;;
+			esac
+			echo "$id: uploading $upload (to $upload_name $upload_to) ..."
+			dput ${ANCILLARY_DPUTCF:+-c $ANCILLARY_DPUTCF} "$upload_to" "$upload"
+		done
+	)
+	rc="$?"
+	echo "$id: ancillary build complete rc=$rc"
 done
