ancillary-bot: report ancillary failures and continue
When an individual ancillary fails we currently exit and miss later
items.  Report failures and continue.

Signed-off-by: Andy Whitcroft <apw@canonical.com>

diff --git a/ancillary-bot/ancillary-builder b/ancillary-bot/ancillary-builder
--- a/ancillary-bot/ancillary-builder
+++ b/ancillary-bot/ancillary-builder
@@ -40,8 +40,9 @@ do
 				echo "$id: re-uploading $upload (to $upload_name $upload_to) ..."
 				dput ${ANCILLARY_DPUTCF:+-c $ANCILLARY_DPUTCF} "$upload_to" "$upload"
 			done
-		) || exit "$?"
-		echo "$id: complete"
+		)
+		arc="$?"
+		echo "$id: complete, rc=$arc"
 		continue
 	fi
 
@@ -59,6 +60,8 @@ do
 		echo "$id: extracting source ..."
 		dpkg-source -x $source*.dsc
 
+		arc=0
+
 		# Confirm this is the appropriate form.
 		if [ -d $source-*/debian/ancillary ]; then
 			echo "$id: direct ancillaries present"
@@ -75,7 +78,8 @@ do
 					) || exit "$?"
 					mv ${ancillary}_* ../../..
 				done
-			) || exit "$?"
+			)
+			arc="$?"
 
 		elif [ -f $source-*/debian/scripts/gen-ancillary ]; then
 			echo "$id: triggering gen-anciallary"
@@ -87,7 +91,8 @@ do
 					echo "$id: gen-ancillary failed rc=$rc" 1>&2
 				fi
 				exit "$rc"
-			) || exit "$?"
+			)
+			arc="$?"
 		
 		elif [ -f $source-*/debian/scripts/gen-rules.lrm ]; then
 			(
@@ -102,12 +107,18 @@ do
 				sed -i -e '1s/linux-restricted-generate/linux-restricted-signatures/' debian/changelog
 				debian/rules clean
 				dpkg-buildpackage --no-sign -nc -S
-			) || exit "$?"
+			)
+			arc="$?"
 
 		else
 			echo "$id: non-ancillary form, marking ignored"
 			touch "ignore"
-			exit 0
+			arc="1"
+		fi
+
+		if [ "$arc" != 0 ]; then
+			echo "$id: ancillary build failed, rc=$arc"
+			continue
 		fi
 
 		for upload in *_source.changes
