ancillary-bot: retry uploads
When uploads fail we will notice because we have no upload files.  As
dput honours these files we can simply retry the uploads each time we
scan.

Signed-off-by: Andy Whitcroft <apw@canonical.com>

diff --git a/ancillary-bot/lrm-ancillary-builder b/ancillary-bot/lrm-ancillary-builder
--- a/ancillary-bot/lrm-ancillary-builder
+++ b/ancillary-bot/lrm-ancillary-builder
@@ -28,6 +28,14 @@ do
 			echo "$id: ignored (v3)"
 			continue
 		fi
+		(
+			cd "$id" || exit 1
+			# If the uploads failed, the we should retry them periodically.
+			for changes in *_source.changes
+			do
+				dput ${ANCILLARY_DPUTCF:+-c $ANCILLARY_DPUTCF} "$ppa_ps" "$changes"
+			done
+		) || exit "$?"
 		echo "$id: complete"
 		continue
 	fi
